### ISSUE TITLE
Feature request: Custom run commands

### ISSUE THREAD

**Issue by RobinCoffee** [RainbowC0/TermuC#8]
I have a C project that is multiple files and I use the program just (basically a command runner) to build and run my project and also do any linting or other operations. I really like this editor so far but I would like to be able to set the run button to be a command other than the compiler. E.g. I could set it to run "just run" and then have just run the commands for building and running the executable. I would be willing to attempt to contribute this feature but I don't have any experience coding in Java. I could see other people wanting to program with a complicated makefile or something like that, which would be another use for this. Let me know what you think. Thank you for the awesome app!

**Comment by RainbowC0** [comment]
Project management is a long-term planning. What project structure should TermuC adapt, how a project is organized and how to support some build systems like Makefile, CMake, meson, ninja and etc are under consideration.

There are some temporary solutions. You can add other needed source files to the start of "Compile Flags" option like:

```
b.c c.c module1/d.c -Wall -lm
```

Otherwise, open Termux and change to the root path of your project and compile it manually.

**Comment by RainbowC0** [comment]
The new version v0.1.5 supports simple project management, you can have a try.
